version: "3.8"
services:
  backend:
    container_name: sailsjs_mongodb
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    volumes:
      - ".:/app"
      - /app/node_modules
    networks:
      - trandung
  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - trandung
volumes:
  mongodb:
networks:
  trandung: